name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'modules/EKS/**'
      - 'modules/IAM/**'
      - 'modules/RDS/**'
      - 'modules/key/**'
      - 'modules/VPC/**'
      - 'modules/Nat-GW/**'
      - 'modules/NodeGroup/**'
      - 'modules/vpc/**'

  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    # Environment variables can be set here or within steps as needed
    env:
      AWS_REGION: 'us-east-1'  # Adjust as necessary for your AWS region

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.3.2"  # Specify the version of Terraform you are using

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Terraform Output
        run: |
          cd terraform
          terraform output
